In [2]:
import pandas as pd

In [3]:
hp = pd.read_csv("dataset/Hospital_data.csv")

In [4]:
hp.info

<bound method DataFrame.info of                    Date  Children apprehended and placed in CBP custody*  \
0     December 21, 2025                                              6.0
1     December 18, 2025                                             11.0
2     December 17, 2025                                              7.0
3     December 16, 2025                                              8.0
4     December 15, 2025                                             11.0
...                 ...                                              ...
1165                NaN                                              NaN
1166                NaN                                              NaN
1167                NaN                                              NaN
1168                NaN                                              NaN
1169                NaN                                              NaN

      Children in CBP custody  Children transferred out of CBP custody  \
0                        18.0                                     11.0
1                        50.0                                      6.0
2                        31.0                                     11.0
3                        54.0                                     15.0
4                        42.0                                      9.0
...                       ...                                      ...
1165                      NaN                                      NaN
1166                      NaN                                      NaN
1167                      NaN                                      NaN
1168                      NaN                                      NaN
1169                      NaN                                      NaN

     Children in HHS Care  Children discharged from HHS Care
0                   2,484                               14.0
1                   2,472                               16.0
2                   2,481                               10.0
3                   2,468                                9.0
4                   2,470                                7.0
...                   ...                                ...
1165                  NaN                                NaN
1166                  NaN                                NaN
1167                  NaN                                NaN
1168                  NaN                                NaN
1169                  NaN                                NaN

[1170 rows x 6 columns]>

In [5]:
hp.describe()

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children discharged from HHS Care
count,720.000000,720.000000,720.000000,720.000000
mean,93.523611,171.494444,128.668056,173.406944
std,72.646625,126.354965,97.322012,125.702841
min,0.000000,7.000000,0.000000,0.000000
25%,12.000000,36.000000,14.000000,19.750000
50%,99.000000,193.000000,157.000000,181.000000
75%,147.250000,263.250000,199.250000,267.000000
max,333.000000,531.000000,440.000000,505.000000

In [7]:
hp.shape

(1170, 6)

In [6]:
hp.head(5)

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,"December 21, 2025",6.0,18.0,11.0,"2,484",14.0
1,"December 18, 2025",11.0,50.0,6.0,"2,472",16.0
2,"December 17, 2025",7.0,31.0,11.0,"2,481",10.0
3,"December 16, 2025",8.0,54.0,15.0,"2,468",9.0
4,"December 15, 2025",11.0,42.0,9.0,"2,470",7.0

In [7]:
hp.tail(20)

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
1150,NaN,NaN,NaN,NaN,NaN,NaN
1151,NaN,NaN,NaN,NaN,NaN,NaN
1152,NaN,NaN,NaN,NaN,NaN,NaN
1153,NaN,NaN,NaN,NaN,NaN,NaN
1154,NaN,NaN,NaN,NaN,NaN,NaN
1155,NaN,NaN,NaN,NaN,NaN,NaN
1156,NaN,NaN,NaN,NaN,NaN,NaN
1157,NaN,NaN,NaN,NaN,NaN,NaN
1158,NaN,NaN,NaN,NaN,NaN,NaN
1159,NaN,NaN,NaN,NaN,NaN,NaN
1160,NaN,NaN,NaN,NaN,NaN,NaN
1161,NaN,NaN,NaN,NaN,NaN,NaN
1162,NaN,NaN,NaN,NaN,NaN,NaN
1163,NaN,NaN,NaN,NaN,NaN,NaN
1164,NaN,NaN,NaN,NaN,NaN,NaN
1165,NaN,NaN,NaN,NaN,NaN,NaN
1166,NaN,NaN,NaN,NaN,NaN,NaN
1167,NaN,NaN,NaN,NaN,NaN,NaN
1168,NaN,NaN,NaN,NaN,NaN,NaN
1169,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
hp.isnull().sum()

Date                                               450
Children apprehended and placed in CBP custody*    450
Children in CBP custody                            450
Children transferred out of CBP custody            450
Children in HHS Care                               450
Children discharged from HHS Care                  450
dtype: int64

In [9]:
hp.duplicated().sum()

np.int64(449)

In [10]:
hp[hp.duplicated()]

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
721,NaN,NaN,NaN,NaN,NaN,NaN
722,NaN,NaN,NaN,NaN,NaN,NaN
723,NaN,NaN,NaN,NaN,NaN,NaN
724,NaN,NaN,NaN,NaN,NaN,NaN
725,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
1165,NaN,NaN,NaN,NaN,NaN,NaN
1166,NaN,NaN,NaN,NaN,NaN,NaN
1167,NaN,NaN,NaN,NaN,NaN,NaN
1168,NaN,NaN,NaN,NaN,NaN,NaN
1169,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
hp= hp.dropna(how ="all")

In [12]:
hp.describe()

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children discharged from HHS Care
count,720.000000,720.000000,720.000000,720.000000
mean,93.523611,171.494444,128.668056,173.406944
std,72.646625,126.354965,97.322012,125.702841
min,0.000000,7.000000,0.000000,0.000000
25%,12.000000,36.000000,14.000000,19.750000
50%,99.000000,193.000000,157.000000,181.000000
75%,147.250000,263.250000,199.250000,267.000000
max,333.000000,531.000000,440.000000,505.000000

In [13]:
hp.info()

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 6 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Date                                             720 non-null    str
 1   Children apprehended and placed in CBP custody*  720 non-null    float64
 2   Children in CBP custody                          720 non-null    float64
 3   Children transferred out of CBP custody          720 non-null    float64
 4   Children in HHS Care                             720 non-null    str
 5   Children discharged from HHS Care                720 non-null    float64
dtypes: float64(4), str(2)
memory usage: 33.9 KB

In [14]:
hp.isnull()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
715,False,False,False,False,False,False
716,False,False,False,False,False,False
717,False,False,False,False,False,False
718,False,False,False,False,False,False
719,False,False,False,False,False,False

In [15]:
hp.duplicated().sum()

np.int64(0)

In [16]:
hp["Date"].dtype

In [17]:
hp["Date"] = pd.to_datetime(hp["Date"])

In [18]:
hp["Date"].dtype

dtype('<M8[us]')

In [19]:
hp["Date"].head(10)

0   2025-12-21
1   2025-12-18
2   2025-12-17
3   2025-12-16
4   2025-12-15
5   2025-12-14
6   2025-12-11
7   2025-12-10
8   2025-12-09
9   2025-12-08
Name: Date, dtype: datetime64[us]

In [20]:
hp["Date"].tail(10)

710   2023-02-02
711   2023-02-01
712   2023-01-31
713   2023-01-30
714   2023-01-29
715   2023-01-25
716   2023-01-24
717   2023-01-23
718   2023-01-22
719   2023-01-12
Name: Date, dtype: datetime64[us]

In [21]:
hp = hp.sort_values("Date")

In [22]:
hp.head(10)

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
719,2023-01-12,33.0,53.0,34.0,"6,566",436.0
718,2023-01-22,32.0,49.0,39.0,"7,122",227.0
717,2023-01-23,32.0,50.0,39.0,"7,280",181.0
716,2023-01-24,47.0,42.0,47.0,"7,433",175.0
715,2023-01-25,20.0,22.0,41.0,"7,538",180.0
714,2023-01-29,23.0,45.0,11.0,"7,472",303.0
713,2023-01-30,34.0,54.0,29.0,"7,743",196.0
712,2023-01-31,26.0,36.0,36.0,"7,803",158.0
711,2023-02-01,25.0,32.0,27.0,"7,903",231.0
710,2023-02-02,15.0,13.0,23.0,"7,879",298.0

In [23]:
hp.tail(10)

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
9,2025-12-08,9.0,27.0,9.0,"2,440",4.0
8,2025-12-09,4.0,30.0,7.0,"2,443",8.0
7,2025-12-10,10.0,54.0,5.0,"2,439",9.0
6,2025-12-11,7.0,47.0,9.0,"2,437",10.0
5,2025-12-14,8.0,35.0,4.0,"2,462",8.0
4,2025-12-15,11.0,42.0,9.0,"2,470",7.0
3,2025-12-16,8.0,54.0,15.0,"2,468",9.0
2,2025-12-17,7.0,31.0,11.0,"2,481",10.0
1,2025-12-18,11.0,50.0,6.0,"2,472",16.0
0,2025-12-21,6.0,18.0,11.0,"2,484",14.0

In [24]:
hp["Date"].max()

Timestamp('2025-12-21 00:00:00')

In [25]:
hp["Date"].min()

Timestamp('2023-01-12 00:00:00')

In [26]:
(hp["Date"].max()-hp["Date"].min()).days + 1

1075

In [27]:
hp["Date"].nunique()

720

In [28]:
all_dates = pd.date_range(
    start=hp["Date"].min(),
    end=hp["Date"].max(),
    freq="D"
)

In [29]:
hp.head(10)

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
719,2023-01-12,33.0,53.0,34.0,"6,566",436.0
718,2023-01-22,32.0,49.0,39.0,"7,122",227.0
717,2023-01-23,32.0,50.0,39.0,"7,280",181.0
716,2023-01-24,47.0,42.0,47.0,"7,433",175.0
715,2023-01-25,20.0,22.0,41.0,"7,538",180.0
714,2023-01-29,23.0,45.0,11.0,"7,472",303.0
713,2023-01-30,34.0,54.0,29.0,"7,743",196.0
712,2023-01-31,26.0,36.0,36.0,"7,803",158.0
711,2023-02-01,25.0,32.0,27.0,"7,903",231.0
710,2023-02-02,15.0,13.0,23.0,"7,879",298.0

In [30]:
len(all_dates)

1075

In [31]:
len(hp["Date"])

720

In [32]:
missing_dates = all_dates.difference(hp["Date"])

In [33]:
missing_dates

DatetimeIndex(['2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-26',
               ...
               '2025-11-22', '2025-11-26', '2025-11-28', '2025-11-29',
               '2025-12-05', '2025-12-06', '2025-12-12', '2025-12-13',
               '2025-12-19', '2025-12-20'],
              dtype='datetime64[us]', length=355, freq=None)

In [34]:
hp = hp.set_index("Date").reindex(all_dates)

In [35]:
hp

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
2023-01-12,33.0,53.0,34.0,"6,566",436.0
2023-01-13,NaN,NaN,NaN,NaN,NaN
2023-01-14,NaN,NaN,NaN,NaN,NaN
2023-01-15,NaN,NaN,NaN,NaN,NaN
2023-01-16,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
2025-12-17,7.0,31.0,11.0,"2,481",10.0
2025-12-18,11.0,50.0,6.0,"2,472",16.0
2025-12-19,NaN,NaN,NaN,NaN,NaN
2025-12-20,NaN,NaN,NaN,NaN,NaN
2025-12-21,6.0,18.0,11.0,"2,484",14.0

In [36]:
hp.shape

(1075, 5)

In [37]:
hp.isnull().sum()

Children apprehended and placed in CBP custody*    355
Children in CBP custody                            355
Children transferred out of CBP custody            355
Children in HHS Care                               355
Children discharged from HHS Care                  355
dtype: int64

In [38]:
hp[hp.isnull().all(axis = 1)]

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
2023-01-13,NaN,NaN,NaN,NaN,NaN
2023-01-14,NaN,NaN,NaN,NaN,NaN
2023-01-15,NaN,NaN,NaN,NaN,NaN
2023-01-16,NaN,NaN,NaN,NaN,NaN
2023-01-17,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
2025-12-06,NaN,NaN,NaN,NaN,NaN
2025-12-12,NaN,NaN,NaN,NaN,NaN
2025-12-13,NaN,NaN,NaN,NaN,NaN
2025-12-19,NaN,NaN,NaN,NaN,NaN
2025-12-20,NaN,NaN,NaN,NaN,NaN

In [39]:
hp[hp["Children in CBP custody"]>hp["Children transferred out of CBP custody"]]

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
2023-01-12,33.0,53.0,34.0,"6,566",436.0
2023-01-22,32.0,49.0,39.0,"7,122",227.0
2023-01-23,32.0,50.0,39.0,"7,280",181.0
2023-01-29,23.0,45.0,11.0,"7,472",303.0
2023-01-30,34.0,54.0,29.0,"7,743",196.0
...,...,...,...,...,...
2025-12-15,11.0,42.0,9.0,"2,470",7.0
2025-12-16,8.0,54.0,15.0,"2,468",9.0
2025-12-17,7.0,31.0,11.0,"2,481",10.0
2025-12-18,11.0,50.0,6.0,"2,472",16.0
2025-12-21,6.0,18.0,11.0,"2,484",14.0

In [40]:
hp[hp["Children in CBP custody"]>hp["Children transferred out of CBP custody"]].sum()

Children apprehended and placed in CBP custody*                                              59477.0
Children in CBP custody                                                                     110412.0
Children transferred out of CBP custody                                                      77549.0
Children in HHS Care                               6,5667,1227,2807,4727,7437,9037,5867,7207,9157...
Children discharged from HHS Care                                                           103538.0
dtype: object

In [41]:
(hp["Children in CBP custody"]<hp["Children transferred out of CBP custody"]).sum()

np.int64(86)

In [42]:
hp[hp["Children in CBP custody"]<hp["Children transferred out of CBP custody"]].sum()

Children apprehended and placed in CBP custody*                                               7753.0
Children in CBP custody                                                                      12928.0
Children transferred out of CBP custody                                                      14956.0
Children in HHS Care                               7,4337,5387,8797,9787,9147,9308,0548,0178,7908...
Children discharged from HHS Care                                                            20745.0
dtype: object

In [43]:
hp["analogy_transfer"]=(hp["Children in CBP custody"]<hp["Children transferred out of CBP custody"])

In [44]:
hp

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,analogy_transfer
2023-01-12,33.0,53.0,34.0,"6,566",436.0,False
2023-01-13,NaN,NaN,NaN,NaN,NaN,False
2023-01-14,NaN,NaN,NaN,NaN,NaN,False
2023-01-15,NaN,NaN,NaN,NaN,NaN,False
2023-01-16,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...
2025-12-17,7.0,31.0,11.0,"2,481",10.0,False
2025-12-18,11.0,50.0,6.0,"2,472",16.0,False
2025-12-19,NaN,NaN,NaN,NaN,NaN,False
2025-12-20,NaN,NaN,NaN,NaN,NaN,False
2025-12-21,6.0,18.0,11.0,"2,484",14.0,False

In [46]:
hp["Children in HHS Care"].dtype

In [47]:
hp["Children discharged from HHS Care"].dtype

dtype('float64')

In [48]:
hp["Children discharged from HHS Care"] = hp["Children discharged from HHS Care"].astype(float)

In [49]:
hp["Children discharged from HHS Care"].dtype

dtype('float64')

In [50]:
hp["Children in HHS Care"]=hp["Children in HHS Care"].str.replace(",", "", regex=False).astype(float)

In [51]:
(hp["Children discharged from HHS Care"]>hp["Children in HHS Care"]).sum()

np.int64(0)

In [52]:
hp["system load"]= hp["Children in CBP custody"] + hp["Children in HHS Care"]

In [53]:
hp["Net daily intake"]= hp["Children transferred out of CBP custody"] -  hp["Children discharged from HHS Care"]

In [54]:
hp.head(10)

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,analogy_transfer,system load,Net daily intake
2023-01-12,33.0,53.0,34.0,6566.0,436.0,False,6619.0,-402.0
2023-01-13,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
2023-01-14,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
2023-01-15,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
2023-01-16,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
2023-01-17,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
2023-01-18,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
2023-01-19,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
2023-01-20,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
2023-01-21,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN

In [83]:
hp

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,analogy_transfer,system load,Net daily intake,high load,High_Load_Group,High_Load_Duration,Sustained_High_Load,7_day_avg,14_day_avg,Strain_Group,Strain_Duration,Prolonged_Strain
0,2023-01-12,33.0,53.0,34.0,6566.0,436.0,False,6619.0,-402.0,True,1,1,False,6619.0,6619.0,1,0,False
1,2023-01-13,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.0,6619.0,1,0,False
2,2023-01-14,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.0,6619.0,1,0,False
3,2023-01-15,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.0,6619.0,1,0,False
4,2023-01-16,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.0,6619.0,1,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1070,2025-12-17,7.0,31.0,11.0,2481.0,10.0,False,2512.0,1.0,False,204,0,False,2505.4,2487.0,179,0,False
1071,2025-12-18,11.0,50.0,6.0,2472.0,16.0,False,2522.0,-10.0,False,204,0,False,2513.0,2493.5,179,0,False
1072,2025-12-19,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,204,0,False,2513.0,2493.5,179,0,False
1073,2025-12-20,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,204,0,False,2513.0,2493.5,179,0,False
1074,2025-12-21,6.0,18.0,11.0,2484.0,14.0,False,2502.0,-3.0,False,204,0,False,2514.0,2498.4,179,0,False

In [86]:
hp["care load"] = hp["system load"].pct_change()*100

In [87]:
hp["system load"].dtype

dtype('float64')

In [88]:
hp["Backlog indicator"] = hp["Net daily intake"]>0

In [89]:
hp.head(10)

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,analogy_transfer,system load,Net daily intake,high load,High_Load_Group,High_Load_Duration,Sustained_High_Load,7_day_avg,14_day_avg,Strain_Group,Strain_Duration,Prolonged_Strain,care load,Backlog indicator
0,2023-01-12,33.0,53.0,34.0,6566.0,436.0,False,6619.0,-402.0,True,1,1,False,6619.0,6619.0,1,0,False,NaN,False
1,2023-01-13,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.0,6619.0,1,0,False,NaN,False
2,2023-01-14,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.0,6619.0,1,0,False,NaN,False
3,2023-01-15,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.0,6619.0,1,0,False,NaN,False
4,2023-01-16,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.0,6619.0,1,0,False,NaN,False
5,2023-01-17,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.0,6619.0,1,0,False,NaN,False
6,2023-01-18,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.0,6619.0,1,0,False,NaN,False
7,2023-01-19,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,NaN,6619.0,1,0,False,NaN,False
8,2023-01-20,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,NaN,6619.0,1,0,False,NaN,False
9,2023-01-21,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,NaN,6619.0,1,0,False,NaN,False

In [ ]:
hp.tail(10)

In [56]:
hp["high load"] = hp["system load"] > hp["system load"].mean()

In [57]:
hp["high load"].value_counts()

high load
False    646
True     429
Name: count, dtype: int64

In [58]:
hp["system load"].mean()

np.float64(6232.769444444444)

In [59]:
hp["High_Load_Group"] = (
    hp["high load"] != hp["high load"].shift()
).cumsum()

In [60]:
hp["High_Load_Duration"] = (
    hp.groupby("High_Load_Group")["high load"]
    .transform("sum"))

In [61]:
hp["Sustained_High_Load"] = (
    hp["high load"] &
    (hp["High_Load_Duration"] >= 3)
)

In [62]:
hp["Sustained_High_Load"].value_counts()

Sustained_High_Load
False    664
True     411
Name: count, dtype: int64

In [63]:
hp["7_day_avg"] = hp["system load"].rolling(7,min_periods = 1).mean()

In [64]:
hp["14_day_avg"]= hp["system load"].rolling(14,min_periods= 1).mean()

In [65]:
hp.head(30)

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,analogy_transfer,system load,Net daily intake,high load,High_Load_Group,High_Load_Duration,Sustained_High_Load,7_day_avg,14_day_avg
2023-01-12,33.0,53.0,34.0,6566.0,436.0,False,6619.0,-402.0,True,1,1,False,6619.000000,6619.000000
2023-01-13,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.000000,6619.000000
2023-01-14,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.000000,6619.000000
2023-01-15,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.000000,6619.000000
2023-01-16,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.000000,6619.000000
2023-01-17,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.000000,6619.000000
2023-01-18,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,6619.000000,6619.000000
2023-01-19,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,NaN,6619.000000
2023-01-20,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,NaN,6619.000000
2023-01-21,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,2,0,False,NaN,6619.000000
2023-01-22,32.0,49.0,39.0,7122.0,227.0,False,7171.0,-188.0,True,3,4,True,7171.000000,6895.000000
2023-01-23,32.0,50.0,39.0,7280.0,181.0,False,7330.0,-142.0,True,3,4,True,7250.500000,7040.000000
2023-01-24,47.0,42.0,47.0,7433.0,175.0,True,7475.0,-128.0,True,3,4,True,7325.333333,7148.750000
2023-01-25,20.0,22.0,41.0,7538.0,180.0,True,7560.0,-139.0,True,3,4,True,7384.000000,7231.000000
2023-01-26,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,4,0,False,7384.000000,7384.000000
2023-01-27,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,4,0,False,7384.000000,7384.000000
2023-01-28,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,4,0,False,7384.000000,7384.000000
2023-01-29,23.0,45.0,11.0,7472.0,303.0,False,7517.0,-292.0,True,5,5,True,7470.500000,7410.600000
2023-01-30,34.0,54.0,29.0,7743.0,196.0,False,7797.0,-167.0,True,5,5,True,7587.250000,7475.000000
2023-01-31,26.0,36.0,36.0,7803.0,158.0,False,7839.0,-122.0,True,5,5,True,7678.250000,7527.000000
2023-02-01,25.0,32.0,27.0,7903.0,231.0,False,7935.0,-204.0,True,5,5,True,7772.000000,7578.000000
2023-02-02,15.0,13.0,23.0,7879.0,298.0,True,7892.0,-275.0,True,5,5,True,7796.000000,7612.888889
2023-02-03,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,6,0,False,7796.000000,7612.888889
2023-02-04,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,6,0,False,7796.000000,7612.888889
2023-02-05,16.0,18.0,15.0,7586.0,342.0,False,7604.0,-327.0,True,7,5,True,7813.400000,7661.000000
2023-02-06,11.0,22.0,12.0,7720.0,196.0,False,7742.0,-184.0,True,7,5,True,7802.400000,7706.777778
2023-02-07,16.0,20.0,20.0,7855.0,200.0,False,7875.0,-180.0,True,7,5,True,7809.600000,7751.222222
2023-02-08,93.0,196.0,169.0,7915.0,317.0,False,8111.0,-148.0,True,7,5,True,7844.800000,7812.444444
2023-02-09,124.0,234.0,161.0,7908.0,353.0,False,8142.0,-192.0,True,7,5,True,7894.800000,7845.400000
2023-02-10,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,8,0,False,7894.800000,7845.400000

In [66]:
hp["system load"].notna().sum()

np.int64(720)

In [67]:
hp["Strain_Group"] = (
    hp["Sustained_High_Load"] != hp["Sustained_High_Load"].shift()
).cumsum()

In [68]:
hp["Strain_Duration"] = (
    hp.groupby("Strain_Group")["Sustained_High_Load"]
      .transform("sum")
)

In [69]:
hp["Prolonged_Strain"] = (
    hp["Sustained_High_Load"] &
    (hp["Strain_Duration"] >= 3)
)

In [70]:
hp[hp["Prolonged_Strain"]][
    [ "system load", "Prolonged_Strain", "Strain_Duration"]
]

            system load  Prolonged_Strain  Strain_Duration
2023-01-22       7171.0              True                4
2023-01-23       7330.0              True                4
2023-01-24       7475.0              True                4
2023-01-25       7560.0              True                4
2023-01-29       7517.0              True                5
...                 ...               ...              ...
2024-12-22       6850.0              True                5
2024-12-23       6842.0              True                5
2024-12-24       6926.0              True                5
2024-12-25       6851.0              True                5
2024-12-26       6829.0              True                5

[411 rows x 3 columns]

In [71]:
hp.describe()

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care,system load,Net daily intake,High_Load_Group,High_Load_Duration,7_day_avg,14_day_avg,Strain_Group,Strain_Duration
count,720.000000,720.000000,720.000000,720.000000,720.000000,720.000000,720.000000,1075.000000,1075.000000,1072.000000,1075.000000,1075.000000,1075.000000
mean,93.523611,171.494444,128.668056,6061.275000,173.406944,6232.769444,-44.738889,134.495814,1.831628,6246.321657,6261.918137,121.508837,1.805581
std,72.646625,126.354965,97.322012,2833.070109,125.702841,2918.458078,95.863856,68.650253,2.316350,2909.816167,2893.270284,59.849755,2.327147
min,0.000000,7.000000,0.000000,1972.000000,0.000000,2002.000000,-465.000000,1.000000,0.000000,2009.200000,2011.300000,1.000000,0.000000
25%,12.000000,36.000000,14.000000,2467.750000,19.750000,2500.750000,-94.250000,72.000000,0.000000,2513.000000,2506.428571,67.000000,0.000000
50%,99.000000,193.000000,157.000000,6406.500000,181.000000,6633.500000,-11.500000,151.000000,0.000000,6619.000000,6619.000000,144.000000,0.000000
75%,147.250000,263.250000,199.250000,8010.250000,267.000000,8249.500000,5.250000,204.000000,5.000000,8268.650000,8281.050000,179.000000,5.000000
max,333.000000,531.000000,440.000000,11516.000000,505.000000,11762.000000,206.000000,204.000000,6.000000,11545.250000,11432.875000,179.000000,6.000000

In [73]:
hp.columns

Index(['Children apprehended and placed in CBP custody*',
       'Children in CBP custody', 'Children transferred out of CBP custody',
       'Children in HHS Care', 'Children discharged from HHS Care',
       'analogy_transfer', 'system load', 'Net daily intake', 'high load',
       'High_Load_Group', 'High_Load_Duration', 'Sustained_High_Load',
       '7_day_avg', '14_day_avg', 'Strain_Group', 'Strain_Duration',
       'Prolonged_Strain'],
      dtype='str')

In [76]:
hp = hp.reset_index()

In [74]:
hp.to_csv("hospital data.csv",index=False)

In [77]:
hp.columns

Index(['index', 'Children apprehended and placed in CBP custody*',
       'Children in CBP custody', 'Children transferred out of CBP custody',
       'Children in HHS Care', 'Children discharged from HHS Care',
       'analogy_transfer', 'system load', 'Net daily intake', 'high load',
       'High_Load_Group', 'High_Load_Duration', 'Sustained_High_Load',
       '7_day_avg', '14_day_avg', 'Strain_Group', 'Strain_Duration',
       'Prolonged_Strain'],
      dtype='str')

In [78]:
hp.rename(columns={"index": "Date"}, inplace=True)

In [79]:
hp.columns

Index(['Date', 'Children apprehended and placed in CBP custody*',
       'Children in CBP custody', 'Children transferred out of CBP custody',
       'Children in HHS Care', 'Children discharged from HHS Care',
       'analogy_transfer', 'system load', 'Net daily intake', 'high load',
       'High_Load_Group', 'High_Load_Duration', 'Sustained_High_Load',
       '7_day_avg', '14_day_avg', 'Strain_Group', 'Strain_Duration',
       'Prolonged_Strain'],
      dtype='str')

In [93]:
hp["Accumulation rate"]= hp["system load"].pct_change()*100

In [94]:
hp.to_csv("hospital clean data.csv",index=False)